Document: teams-guest-login
Title: Debian teams-guest-login Manual
Author: <insert document author here>
Abstract: This manual describes what teams-guest-login is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/teams-guest-login/teams-guest-login.sgml.gz

Format: postscript
Files: /usr/share/doc/teams-guest-login/teams-guest-login.ps.gz

Format: text
Files: /usr/share/doc/teams-guest-login/teams-guest-login.text.gz

Format: HTML
Index: /usr/share/doc/teams-guest-login/html/index.html
Files: /usr/share/doc/teams-guest-login/html/*.html
